spring:
  datasource:
    url: jdbc:mysql://47.110.233.147:53306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true&useSSL=false
    username: root
    password: Hrt#4<.29dP[>vW
    driver-class-name: com.mysql.jdbc.Driver
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
bebetter:
  web:
    cors:
      allowCredentials: true